# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "LL-Testing"
description = "LL-Testing."

[find-package.LLVM]
[find-package.Clang]

[target.LL-Testing]
type = "executable"
sources = ["src/main.cpp"]
include-directories = ["${LLVM_INCLUDE_DIRS}", "${CLANG_INCLUDE_DIRS}"]
link-directories = ["${LLVM_LIBRARY_DIRS}", "${CLANG_LIBRARY_DIRS}"]
compile-definitions = ["${LLVM_DEFINITIONS}", "${CLANG_DEFINITIONS}"]
link-libraries = [
"LLVMSupport", 
"LLVMAnalysis",
"LLVMCore",
"LLVMCodeGen"
]

